server:
  port: 9090
spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://localhost:3306/bookings?createDatabaseIfNotExist=true
    username: root
    password: Krd@1204
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    